###
# get amadeus flights offer search
GET http://localhost:3000/amadeus/flight-offers?currencyCode=USD&originLocationCode=TLV&destinationLocationCode=CDG&departureDate=2025-12-10&returnDate=2025-12-20&adults=1&travelClass=ECONOMY&children=0&infants=0&max=10

###
# get amadeus token
POST http://localhost:3000/amadeus

###
# get amadeus hotel offer search
GET http://localhost:3000/amadeus/hotel-offers?hotelIds[]=RTBRSMRC&hotelIds[]=TGBRS838&cityCode=BRS&checkInDate=2025-07-31&checkOutDate=2025-08-02&roomQuantity=1&adults=1&currency=USD

###
# get amadeus hotel offer details
GET http://localhost:3000/amadeus/hotels?cityCode=PAR
